export const DATA_REQUEST = "LOAN_DATA_REQUEST";
export const DATA_FAILURE = "LOAN_DATA_FAILURE";

export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const GET_LOAN_DATA_SUCCESS = "GET_LOAN_DATA_SUCCESS";
export const CREATE_LOAN_DATA_SUCCESS = "CREATE_LOAN_DATA_SUCCESS";
