export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";

export const LOAN_DATA_REQUEST = "LOAN_DATA_REQUEST";
export const LOAN_DATA_SUCCESS = "LOAN_DATA_SUCCESS";
export const LOAN_DATA_FAILURE = "LOAN_DATA_FAILURE";